# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-01-11 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='merchant',
            unique_together=set([('name', 'for_group')]),
        ),
    ]
