# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190903_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
