# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-18 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200111_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
