# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
