# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-15 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20191015_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopgroup',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
