# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-21 10:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shopgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
