# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-01-17 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20200114_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationkey',
            name='date_invited',
            field=models.DateField(default=datetime.date.today, verbose_name='date invited'),
        ),
    ]
