# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-16 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20190903_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['description']},
        ),
        migrations.AddField(
            model_name='item',
            name='cancelled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
