# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-15 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopgroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shopgroup',
            managers=[
            ],
        ),
    ]
