# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191021_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
