# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191021_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ShopGroup'),
        ),
    ]
