# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-12-31 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_shopgroup_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopgroup',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='leader_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
